### ISSUE TITLE
specify path to python in cronjob string?

### ISSUE THREAD

**Issue by simgitlochub** [lazaroblanc/IONOS-DynDNS#4]
Hi I am new to github and not even a programmer - a tinkerer really. First off - thank you very much for writing this python script!  But I haven't been able to get it to work! :( I don't what I am doing, but I think maybe the string has to first specify to execute the script using python3 and include the path to python3 as well, right?
Should it look something rather like this?

*/15 * * * * /usr/bin/python3 ./ionos_dyndns.py --AAAA --api-prefix my_prefix_string --api-secret my_secret_string

**Comment by lazaroblanc** [comment]
Hi @simgitlochub 
Thank you for your feedback.

Your call of the script looks correct.
Is the script executable? Check the file mode...
Do you get any error messages?
Does it work when you execute that line without the cron part? (just `/usr/bin/python3 ./ionos_dyndns.py --AAAA --api-prefix my_prefix_string --api-secret my_secret_string`)

**Comment by simgitlochub** [comment]
Hi! Thank you for your reply!

I checked the file (with the <file> command) and get the result:

 _ionos_dyndns.py: Python script, UTF-8 Unicode text executable_

So i guess it's good to go.
I had a bunch of problems with PIP (pyopenssl was messed up) and other stuff which are fixed now, but here is my current error:

> Traceback (most recent call last):
>   File "ionos_dyndns.py", line 190, in <module>
>     main()
>   File "ionos_dyndns.py", line 90, in main
>     domain = get_domain_from_fqdn(fqdn)
>   File "ionos_dyndns.py", line 139, in get_domain_from_fqdn
>     return re.search(regex, fqdn, re.IGNORECASE).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

**Comment by mricim** [comment]
Same mistake.

The problem seems to be in:
```
def get_domain_from_fqdn(fqdn):
    regex = r"(?:(?:\w|-)+\.)+(\w+\.\w+)$"
    return re.search(regex, fqdn, re.IGNORECASE).group(1)
domain = get_domain_from_fqdn(fqdn)
```
The line `re.search(regex, fqdn, re.IGNORECASE).group(1)` return "**None**" 
If you modified `zone = get_zone(domain)` to `zone = get_zone("domain.com")` or `zone = get_zone(fqdn)` works.
Surely we are doing something wrong, but I don't know what

**Comment by mricim** [comment]
It turns out that the script was configured only to work with **"www."** prefixes in domain names. I've submitted [pull request #6](https://github.com/lazaroblanc/IONOS-DynDNS/pull/6) to make it now accept both **"domain.com"** and the subdomain **"www.domain.com."**

I believe that with these changes, the functionality should be more versatile and address the original concern raised in the issue. It might be beneficial to consider adding additional documentation on how to use the `-H` option to specify the full host name. This would provide clearer guidance for users.

I think this issue can now be closed. I appreciate any further review and suggestions before officially closing it. Thank you!
